
# This file has been generated at Thu Dec 08 11:54:58 2011

from openalea.core import *


__name__ = 'alinea.caribu.visualisation'

__editable__ = True
__description__ = ' Visualisation tools for the Caribu package '
__license__ = ''
__url__ = ''
__alias__ = ['Caribu.Visualisation']
__version__ = '0.0.3'
__authors__ = 'C. Pradal'
__institutes__ = 'CIRAD'
__icon__ = ''


__all__ = ['_67876816', 'gammaTrans_gammaTrans', 'saveImage_saveImage', 'colorScale_colorScale', 'ViewMapOnCan', 'py_canview_plot_can', 'py_canview_read_can']



_67876816 = CompositeNodeFactory(name='Plot CaribuScene',
                             description='3D plot of Caribuscene',
                             category='visualisation',
                             doc='',
                             inputs=[{  'desc': '', 'interface': IStr, 'name': 'CansceneString', 'value': None}],
                             outputs=[{  'desc': '', 'interface': IFileStr, 'name': 'can file'}],
                             elt_factory={  7: ('alinea.caribu.visualisation', 'Plot Can File'),
   8: ('alinea.caribu', 'WriteCan'),
   9: ('openalea.file', 'tmpnam')},
                             elt_connections={  9919168: (9, 0, 8, 1),
   9919180: (8, 0, 7, 0),
   9919192: ('__in__', 0, 8, 0),
   9919204: (7, 0, '__out__', 0)},
                             elt_data={  7: {  'block': False,
         'caption': 'Plot Can File',
         'hide': True,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 138.75,
         'posy': -313.75,
         'priority': 0,
         'user_application': None},
   8: {  'block': False,
         'caption': 'WriteCan',
         'hide': True,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 130.0,
         'posy': -396.25,
         'priority': 0,
         'user_application': None},
   9: {  'block': False,
         'caption': 'tmpnam',
         'hide': True,
         'lazy': False,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 246.25,
         'posy': -473.75,
         'priority': 0,
         'user_application': None},
   '__in__': {  'caption': 'In',
                'hide': True,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 140.0,
                'posy': -506.25,
                'priority': 0},
   '__out__': {  'caption': 'Out',
                 'hide': True,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 165.0,
                 'posy': -232.5,
                 'priority': 0}},
                             elt_value={  7: [(1, 'None')], 8: [], 9: [], '__in__': [], '__out__': []},
                             elt_ad_hoc={  },
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




gammaTrans_gammaTrans = Factory(name='gammaTrans',
                authors='C. Pradal (wralea authors)',
                description='return value normalised and raised at exponent gamma',
                category='Unclassified',
                nodemodule='gammaTrans',
                nodeclass='gammaTrans',
                inputs=[{'interface': None, 'name': 'values', 'value': None, 'desc': ''}, {'interface': IFloat, 'name': 'gamma', 'value': 1, 'desc': ''}, {'interface': IFloat, 'name': 'minval', 'value': None, 'desc': ''}, {'interface': IFloat, 'name': 'maxval', 'value': None, 'desc': ''}],
                outputs=[{'interface': ISequence, 'name': 'res', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




saveImage_saveImage = Factory(name='saveImage',
                authors='C. Pradal, JC Soulie, D. Luquet (wralea authors)',
                description='',
                category='Unclassified',
                nodemodule='saveImage',
                nodeclass='saveImage',
                inputs=[{'interface': IFileStr, 'name': 'image_name', 'value': None, 'desc': ''}, {'interface': IInterface, 'name': 'scene', 'value': None, 'desc': ''}],
                outputs=[{'interface': IInterface, 'name': 'scene', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




colorScale_colorScale = Factory(name='colorScale',
                authors='C. Pradal (wralea authors)',
                description='Produce an plot of the colorscale used by ViewMapOnCan when gamma == 1',
                category='visualisation',
                nodemodule='colorScale',
                nodeclass='colorScale',
                inputs=[{'interface': None, 'name': 'minval', 'value': None, 'desc': 'min value of the data'}, {'interface': IFloat, 'name': 'maxval', 'value': None, 'desc': 'max value of the data'}, {'interface': IStr, 'name': 'label', 'value': None, 'desc': 'axis label'}],
                outputs=[{'interface': None, 'name': 'fig', 'desc': ''}],
                widgetmodule=None,
                widgetclass=None,
               )




ViewMapOnCan = CompositeNodeFactory(name='ViewMapOnCan',
                             description='Plots values on a canestra scene',
                             category='Unclassified',
                             doc='',
                             inputs=[  {  'desc': '', 'interface': IStr, 'name': 'CansceneString', 'value': None},
   {  'desc': '', 'interface': ISequence, 'name': 'Values', 'value': None},
   {  'desc': '',
      'interface': IFloat,
      'name': 'gamma',
      'value': 0.20000000000000001},
   {  'desc': '', 'interface': IFloat, 'name': 'minval', 'value': None},
   {  'desc': '', 'interface': IFloat, 'name': 'minval', 'value': None}],
                             outputs=[{  'desc': '', 'interface': IFileStr, 'name': 'can file'}],
                             elt_factory={  4: ('alinea.caribu.visualisation', 'gammaTrans'),
   5: ('openalea.color', 'colormap'),
   6: ('openalea.function operator', 'map'),
   7: ('alinea.caribu.visualisation', 'Plot Can File'),
   8: ('alinea.caribu', 'WriteCan'),
   9: ('openalea.file', 'tmpnam')},
                             elt_connections={  10019924: ('__in__', 4, 4, 3),
   10019936: ('__in__', 3, 4, 2),
   10019948: (5, 0, 6, 0),
   10019960: ('__in__', 0, 8, 0),
   10019972: (6, 0, 7, 1),
   10019984: (8, 0, 7, 0),
   10019996: (4, 0, 6, 1),
   10020008: ('__in__', 2, 4, 1),
   10020020: ('__in__', 1, 4, 0),
   10020032: (9, 0, 8, 1),
   10020044: (7, 0, '__out__', 0)},
                             elt_data={  4: {  'block': False,
         'caption': 'gammaTrans',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x040BB7F0> : "gammaTrans"',
         'hide': True,
         'id': 4,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 340.27777777777777,
         'posy': -423.61111111111109,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   5: {  'block': False,
         'caption': 'ColorMap',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03B8E230> : "colormap"',
         'hide': True,
         'id': 5,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 270.41666666666652,
         'posy': -368.61111111111114,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   6: {  'block': False,
         'caption': 'map',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03B6EE90> : "map"',
         'hide': True,
         'id': 6,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 416.11111111111103,
         'posy': -283.47222222222229,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   7: {  'block': False,
         'caption': 'Plot Can File',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x040BB870> : "Plot Can File"',
         'hide': True,
         'id': 7,
         'lazy': True,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 120.0,
         'posy': -227.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   8: {  'block': False,
         'caption': 'WriteCan',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x03A49350> : "WriteCan"',
         'hide': True,
         'id': 8,
         'lazy': True,
         'port_hide_changed': set(),
         'posx': 95.0,
         'posy': -308.75,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   9: {  'block': False,
         'caption': 'tmpnam',
         'delay': 0,
         'factory': '<openalea.core.node.NodeFactory object at 0x041F7190> : "tmpnam"',
         'hide': True,
         'id': 9,
         'lazy': False,
         'minimal': False,
         'port_hide_changed': set(),
         'posx': 155.0,
         'posy': -372.5,
         'priority': 0,
         'use_user_color': False,
         'user_application': None,
         'user_color': None},
   '__in__': {  'block': False,
                'caption': 'In',
                'delay': 0,
                'hide': True,
                'id': 0,
                'lazy': True,
                'minimal': False,
                'port_hide_changed': set(),
                'posx': 270.0,
                'posy': -588.5,
                'priority': 0,
                'use_user_color': False,
                'user_application': None,
                'user_color': None},
   '__out__': {  'block': False,
                 'caption': 'Out',
                 'delay': 0,
                 'hide': True,
                 'id': 1,
                 'lazy': True,
                 'minimal': False,
                 'port_hide_changed': set(),
                 'posx': 247.5,
                 'posy': -108.0,
                 'priority': 0,
                 'use_user_color': False,
                 'user_application': None,
                 'user_color': None}},
                             elt_value={  4: [],
   5: [(0, 'None'), (1, '0'), (2, '1'), (3, '250.0'), (4, '20.0')],
   6: [],
   7: [],
   8: [],
   9: [],
   '__in__': [],
   '__out__': []},
                             elt_ad_hoc={  4: {'position': [340.27777777777777, -423.61111111111109], 'userColor': None, 'useUserColor': False},
   5: {'position': [270.41666666666652, -368.61111111111114], 'userColor': None, 'useUserColor': False},
   6: {'position': [416.11111111111103, -283.47222222222229], 'userColor': None, 'useUserColor': False},
   7: {'position': [120.0, -227.5], 'userColor': None, 'useUserColor': False},
   8: {'position': [95.0, -308.75], 'userColor': None, 'useUserColor': False},
   9: {'position': [155.0, -372.5], 'userColor': None, 'useUserColor': False},
   '__in__': {'position': [270.0, -588.5], 'userColor': None, 'useUserColor': False},
   '__out__': {'position': [247.5, -108.0], 'userColor': None, 'useUserColor': False}},
                             lazy=True,
                             eval_algo='LambdaEvaluation',
                             )




py_canview_plot_can = Factory(name='Plot Can File',
                authors='C. Pradal (wralea authors)',
                description='Simple Plot of a can file',
                category='Visualisation.Caribu',
                nodemodule='py_canview',
                nodeclass='plot_can',
                inputs=[{'interface': IFileStr(filter="*.can", save=False), 'name': 'can file'}, {'interface': ISequence, 'name': 'colors', 'value': None}],
                outputs=[{'name': 'Canestra file'}],
                widgetmodule=None,
                widgetclass=None,
               )




py_canview_read_can = Factory(name='Import Can File',
                authors='C. Pradal (wralea authors)',
                description='ld a detailled description of a can file',
                category='IO, Visualisation.Caribu',
                nodemodule='py_canview',
                nodeclass='read_can',
                inputs=[{'interface': IFileStr(filter="*.can", save=False), 'name': 'can file'}],
                outputs=[{'name': 'Canestra Scene'}],
                widgetmodule=None,
                widgetclass=None,
               )




