c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
c_compiler_version:            # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
  - 10                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]
  - 11                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
cxx_compiler_version:          # [unix]
  - 12                         # [linux]
  - 16                         # [osx]
  - 10                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]
  - 11                         # [os.environ.get("CF_CUDA_ENABLED", "False") == "True" and linux]

m2w64_c_compiler:                 # [win]
  - gcc                           # [win]
m2w64_c_compiler_version:         # [win]
  - 5                            # [win]
m2w64_cxx_compiler:               # [win]
  - gxx                           # [win]
m2w64_cxx_compiler_version:       # [win]
  - 5                            # [win]
